### PR TITLE
NoteView Activity Skeleton and debug button

### PR DESCRIPTION
**Pull request by jasonpanelli**
Debug button navigates to NoteView activity from MainActivity

### CODE REVIEW

**Comment by jgarciarovetta** [comment]
As long as you've resolved these conflicts locally and it works it looks good to me

**Comment by jasonpanelli** [comment]
@jgarciarovetta @simonzeiger is "TripView" renamed to "TripViewActivity"?

**Comment by jasonpanelli** [comment]
Resolved Conflicts

**Comment by jgarciarovetta** [comment]
LGTM

**Pull request merged**
